"""Calendar module."""
from app.calendar.calendar_mcp_client import calendar_client
from app.calendar.calendar_tools import (
    create_event,
    create_all_day_event,
    create_recurring_event,
    list_today_events,
    list_tomorrow_events,
    list_upcoming_events,
    list_events_by_date,
    list_week_events,
    get_event_details,
    delete_event,
    search_events,
    check_availability,
    find_free_slots,
    reschedule_event,
    change_event_title,
    add_event_attendee,
    remove_event_attendee,
    check_specific_time,
)

__all__ = [
    "calendar_client",
    "create_event",
    "create_all_day_event",
    "create_recurring_event",
    "list_today_events",
    "list_tomorrow_events",
    "list_upcoming_events",
    "list_events_by_date",
    "list_week_events",
    "get_event_details",
    "delete_event",
    "search_events",
    "check_availability",
    "find_free_slots",
    "reschedule_event",
    "change_event_title",
    "add_event_attendee",
    "remove_event_attendee",
    "check_specific_time",
]
